version: "3.8"

services:
  app:
    container_name: frontend
    image: frontend
    build:
      context: .
      target: frontend
    volumes:
      - ./src:/frontend/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 5173:5173