import { z } from "zod";

export const ReportWadahSchema = z.object({
    id: z.string(),
    date: z.date(),
    tanggal_report: z.date(),
    ukuran_12: z.number(),
    ukuran_14: z.number(),
    ukuran_16: z.number(),
    ukuran_18: z.number(),
    ukuran_20: z.number(),
    tidak_ukuran_panjang: z.number(),
    rusak_panjang: z.number(),
    hanya_wadah_panjang: z.number(),
    hanya_tutup_panjang: z.number(),
    ukuran_650: z.number(),
    ukuran_700: z.number(),
    ukuran_750: z.number(),
    ukuran_800: z.number(),
    ukuran_900: z.number(),
    ukuran_1000: z.number(),
    ukuran_1500: z.number(),
    ukuran_2000: z.number(),
    ukuran_3000: z.number(),
    tidak_ukuran_ml: z.number(),
    rusak_ml: z.number(),
    hanya_wadah_ml: z.number(),
    hanya_tutup_ml: z.number(),
    dokumentasi: z.string(),
    keterangan: z.string(),
    keterangan_tambahan: z.string(),
    status: z.string(),
    email: z.string()
})